defmodule Fakeartist.Wordlist_EN do
  def wxWORDLIST,
    do: %{
      "animal" => [
        "ant",
        "ant-eater",
        "armadillo",
        "badger",
        "beaver",
        "bee",
        "bird",
        "bull",
        "calf",
        "camel",
        "cat",
        "cheetah",
        "chimpanzee",
        "cow",
        "crane",
        "crocodile",
        "deer",
        "dinosaur",
        "dog",
        "dolphin",
        "donkey",
        "duck",
        "eagle",
        "elephant",
        "fish",
        "flamingo",
        "fly",
        "fox",
        "frog",
        "giraffe",
        "goat",
        "goldfish",
        "gorilla",
        "hamster",
        "hippo",
        "horse",
        "jaguar",
        "kangaroo",
        "cat",
        "ladybug",
        "leopard",
        "lion",
        "lizard",
        "lama",
        "lobster",
        "mammoth",
        "monkey",
        "mosquito",
        "octopus",
        "ostrich",
        "otter",
        "owl",
        "oysters",
        "panda",
        "panther",
        "parrot",
        "peacock",
        "pelican",
        "penguin",
        "pig",
        "dove",
        "porcupine",
        "puppy",
        "rabbits",
        "racoon",
        "rat",
        "reindeer",
        "rhino",
        "rooster",
        "scorpio",
        "gull",
        "seahorse",
        "seal",
        "shark",
        "sheep",
        "shrimp",
        "slug",
        "snake",
        "spider",
        "octopus",
        "squirrel",
        "starfish",
        "stork",
        "swan",
        "tadpole",
        "tiger",
        "toad",
        "clown fish",
        "tuna",
        "turkey",
        "turtle",
        "vulture",
        "walrus",
        "whale",
        "wolf",
        "zebra",
        "turtle",
        "buffalo",
        "catfish",
        "chicken",
        "firefly",
        "mammoth",
        "ostrich",
        "peacock",
        "pit bull",
        "bear"
      ],
      "building" => [
        "airport",
        "apartment building",
        "bank",
        "barber shop",
        "barn",
        "bookstore",
        "bowling alley",
        "bus stop",
        "casino",
        "castle",
        "dom",
        "church",
        "circus",
        "court",
        "department store",
        "disco",
        "fire station",
        "gas station",
        "hospital",
        "house",
        "library",
        "lighthouse",
        "shopping mall",
        "villa",
        "movie theater",
        "museum",
        "office building",
        "opera house",
        "palace",
        "pet shop",
        "police station",
        "post office",
        "jail",
        "restaurant",
        "sawmill",
        "school",
        "supermarket",
        "temple",
        "theatre",
        "railway station"
      ],
      "dress" => [
        "bandana",
        "belt",
        "bikini",
        "boots",
        "fly",
        "cap",
        "coat",
        "dress",
        "earmuffs",
        "eye patch",
        "glasses",
        "gloves",
        "hair tie",
        "cap",
        "headband",
        "jacket",
        "jeans",
        "knee pad",
        "gloves",
        "necklace",
        "workwear",
        "pajamas",
        "party hat",
        "a raincoat",
        "sandals",
        "scarf",
        "shirts",
        "shoes",
        "skirt",
        "slippers",
        "sneakers",
        "socks",
        "sombrero",
        "socks",
        "suit",
        "pullover",
        "sweatshirt",
        "swimsuit",
        "T-shirt",
        "tie",
        "trousers",
        "underpants"
      ],
      "country" => [
        "Africa",
        "Usa",
        "Bahamas",
        "Brazil",
        "Canada",
        "China",
        "Egypt",
        "England",
        "Finland",
        "France",
        "Germany",
        "Greece",
        "Hawaii",
        "Holland",
        "India",
        "Iran",
        "Ireland",
        "Israel",
        "Italy",
        "Jamaica",
        "Japan",
        "Mexico",
        "Morocco",
        "North Korea",
        "Pakistan",
        "Russia",
        "Switzerland",
        "Saudi Arabia",
        "Scotland",
        "South Korea",
        "Spain",
        "Syria",
        "Taiwan",
        "Thailand",
        "Turkey",
        "Vietnam"
      ],
      "family" => [
        "aunt",
        "brothers",
        "children",
        "daughter",
        "father",
        "granddaughter",
        "granny",
        "grandmother",
        "grandfather",
        "grandson",
        "husband",
        "mother",
        "nephew",
        "niece",
        "parents",
        "sister",
        "son",
        "stepdaughter",
        "stepson",
        "uncle"
      ],
      "food" => [
        "apple",
        "banana",
        "grill",
        "loaf",
        "brownie",
        "burger",
        "burritos",
        "carrot",
        "cheese",
        "cherry",
        "chocolate",
        "coconut",
        "spaghetti",
        "pizza",
        "lasagne",
        "hot dog",
        "chicken nuggets",
        "cake",
        "dinner",
        "doritos",
        "fast food",
        "fries",
        "hot dog",
        "lollipop",
        "meatball",
        "omelet",
        "pancakes",
        "peanut",
        "cake",
        "plum",
        "pretzel",
        "sandwich",
        "sausage",
        "bowling",
        "soy sauce",
        "salad"
      ],
      "groceries" => [
        "asparagus",
        "avocado",
        "baguette",
        "beans",
        "broccoli",
        "cookies",
        "corn",
        "cabbage",
        "camembert",
        "celery",
        "grain",
        "eggplant",
        "grapefruit",
        "grapes",
        "honey",
        "ketchup",
        "lemon",
        "salad",
        "macaroni",
        "melon",
        "muffin",
        "mushroom",
        "mustard",
        "pasta",
        "onion",
        "orange",
        "pear",
        "peas",
        "pepper",
        "cucumber",
        "pineapple",
        "popcorn",
        "popsicle",
        "potato",
        "cucumbers",
        "pumpkin",
        "radish",
        "seafood",
        "ice",
        "spinach",
        "strawberry",
        "tomatoes",
        "tuna",
        "carrot",
        "watermelon",
        "peach"
      ],
      "drink" => [
        "champagne",
        "red wine",
        "beer",
        "coffee",
        "espresso",
        "sodas",
        "smoothie",
        "six pack",
        "tequila",
        "whiskey",
        "martini",
        "moscow mule",
        "green tea",
        "ovaltine",
        "rivella",
        "coke",
        "prosecco"
      ],
      "instrument" => [
        "accordion",
        "bagpipes",
        "banjo",
        "bass drum",
        "bassoon",
        "bongos",
        "cello",
        "clarinet",
        "cowbell",
        "drum",
        "drums",
        "electric guitar",
        "concert grand",
        "flute",
        "carillon",
        "gong",
        "guitar",
        "harmonica",
        "harp",
        "timpani",
        "lute",
        "mandolin",
        "oboe",
        "piano",
        "piccolo",
        "saxophone",
        "timpani",
        "triangle",
        "trombone",
        "trumpet",
        "tuba",
        "ukulele",
        "violin",
        "xylophone"
      ],
      "Pop Culture" => [
        "Aladdin",
        "Aquaman",
        "Asterix",
        "Transformers",
        "Avatar",
        "Avengers",
        "Batman",
        "Bowser",
        "Catwoman",
        "Garfield",
        "Ironman",
        "Lion King",
        "Pikachu",
        "Star Trek",
        "Starwars",
        "Twilight"
      ],
      "job" => [
        "auditors",
        "actor",
        "artists",
        "athlete",
        "author",
        "baker",
        "banker",
        "barber",
        "beautician",
        "butcher",
        "captain",
        "carpenter",
        "cashier",
        "chauffeur",
        "cook",
        "trainer",
        "criminal",
        "dentist",
        "director",
        "doctor",
        "drummer",
        "engineer",
        "farmer",
        "firefighter",
        "fisherman",
        "gangster",
        "gardener",
        "gymnast",
        "judge",
        "lawyer",
        "wizard",
        "post man",
        "mechanic",
        "milkman",
        "musician",
        "nurse",
        "painter",
        "pilot",
        "plumber",
        "poet",
        "police officer",
        "politician",
        "priest",
        "princess",
        "printer",
        "professor",
        "rock star",
        "sailor",
        "seller",
        "sheriff",
        "cobbler",
        "soldier",
        "surgeon",
        "cutter",
        "teacher",
        "vet",
        "waiter",
        "warrior",
        "watchmaker",
        "wrestler",
        "assassin",
        "director",
        "gangster",
        "gardener",
        "wizard",
        "princess",
        "waitress",
        "wrestler",
        "butcher",
        "captain",
        "cashier",
        "cowgirl",
        "dentist",
        "drummer",
        "gymnast",
        "post man",
        "mechanic",
        "milkman",
        "musician",
        "nurse",
        "painter",
        "pilot",
        "plumber",
        "poet",
        "police officer",
        "politician",
        "priest",
        "princess",
        "printer",
        "professor",
        "rock star",
        "sailor",
        "seller",
        "sheriff",
        "cobbler",
        "soldier",
        "surgeon",
        "cutter",
        "teacher",
        "vet",
        "waiter",
        "warrior",
        "watchmaker",
        "wrestler",
        "assassin",
        "director",
        "gangster",
        "gardener",
        "wizard",
        "princess",
        "waitress",
        "wrestler",
        "butcher",
        "captain",
        "cashier",
        "cowgirl",
        "dentist",
        "drummer",
        "gymnast",
        "milkman",
        "painter",
        "plumber",
        "pool boy",
        "sheriff",
        "soldier",
        "surgeon",
        "teacher",
        "warrior",
        "artists",
        "barber",
        "cowboy",
        "doctor",
        "farmer"
      ],
      "sports" => [
        "archery",
        "athletics",
        "badminton",
        "baseball",
        "basketball",
        "bowling",
        "boxing",
        "canoeing",
        "motor race",
        "biking",
        "fencing",
        "fishing",
        "soccer",
        "frisbee",
        "golf",
        "gymnastics",
        "hang gliding",
        "ice hockey",
        "horse race",
        "spear",
        "jogging",
        "judo",
        "skipping rope",
        "karate",
        "long jump",
        "mini golf",
        "motorcycle racing",
        "ping-pong",
        "polo",
        "rowing",
        "rugby",
        "sailing",
        "diving",
        "shoot",
        "skiing",
        "sledding",
        "snowboarding",
        "squash",
        "swim",
        "table tennis",
        "tennis",
        "triathlon",
        "volleyball",
        "weightlifting",
        "baseball",
        "dumbbell",
        "soccer",
        "goalposts",
        "golf club",
        "halfpipe",
        "handball",
        "ice skating",
        "skipping rope",
        "long jump",
        "mini golf",
        "olympic games",
        "ping-pong",
        "sledding",
        "swim",
        "archery",
        "bowling",
        "fencing",
        "fishing",
        "home run",
        "spear",
        "referee",
        "boxing"
      ],
      "vehicle" => [
        "plane",
        "bicycle",
        "boat",
        "bus",
        "automobile",
        "dog sled",
        "forklift",
        "golf cart",
        "helicopter",
        "horse",
        "jet",
        "minivan",
        "motorcycle",
        "Porsche",
        "race car",
        "rowboat",
        "sailboat",
        "scooter",
        "ship",
        "subway",
        "taxi",
        "tow truck",
        "tractor",
        "train",
        "tricycle",
        "truck",
        "unicycle",
        "zeppelin"
      ],
      "weapon" => [
        "atomic bomb",
        "barbed wire",
        "bayonet",
        "bazooka",
        "blowpipe",
        "bomb",
        "bow and arrow",
        "cannon",
        "catapult",
        "chainsaw",
        "baton",
        "crossbow",
        "crowbar",
        "dynamite",
        "grenade",
        "hammer",
        "hand grenade",
        "pistol",
        "knife",
        "land mine",
        "rocket",
        "revolver",
        "gun",
        "saw",
        "scissors",
        "screwdriver",
        "shotgun",
        "spear",
        "sword",
        "tank",
        "torpedo"
      ],
      "event" => [
        "birthday",
        "choice",
        "hanukkah",
        "flea market",
        "funeral",
        "wedding",
        "divorce"
      ],
      "valuables" => [
        "bracelet",
        "crystal",
        "diamond",
        "emerald",
        "jewellery"
      ],
      "games" => [
        "Scotland Yard",
        "Scrabble",
        "Monopoly",
        "Pinball"
      ],
      "toy" => [
        "hulahoop",
        "swing",
        "balloon",
        "tricycle",
        "gameboy"
      ],
      "tool" => [
        "chainsaw",
        "scissors",
        "tweezers",
        "compass",
        "crowbar",
        "dustpan",
        "stapler"
      ],
      "furniture" => [
        "waterbed",
        "bathtub",
        "bunk bed",
        "cabinet",
        "barstool",
        "bookshelf",
        "dresser"
      ],
      "care products" => [
        "lipstick",
        "perfume",
        "shampoo",
        "nail file",
        "suncream",
        "hair colour",
        "hair gel",
        "mascara"
      ],
      "medicine" => [
        "crutches",
        "dentures",
        "first aid",
        "a headache",
        "hospital",
        "medication",
        "seasick",
        "suntan",
        "vaccine",
        "vitamins"
      ],
      "plant" => [
        "palm tree",
        "pinecone",
        "pine tree",
        "primrose",
        "cactus",
        "seaweed",
        "bamboo",
        "carrot",
        "celery",
        "cherry",
        "garlic",
        "grapes"
      ],
      "place" => [
        "hong kong",
        "new york",
        "moscow",
        "zurich",
        "basel",
        "bern",
        "berlin",
        "paris",
        "mallorca",
        "amsterdam"
      ],
      "anatomy" => [
        "spine",
        "forehead",
        "moustache",
        "nose hair",
        "shoulder",
        "skeleton",
        "tentacle",
        "whiskers",
        "eyeball",
        "eyebrows",
        "eyelashes",
        "kneecap",
        "ankle",
        "stomach",
        "unibrow",
        "penis"
      ],
      "music" => [
        "bagpipes",
        "guitar",
        "daft punk",
        "macarena",
        "jukebox",
        "skrillex",
        "trombone",
        "beatles",
        "beyoncé",
        "blondie",
        "bon jovi",
        "drums",
        "dubstep",
        "nirvana",
        "outkast",
        "shakira",
        "ukulele"
      ],
      "mythology" => [
        "gripping",
        "atlantis",
        "hercules",
        "minotaur",
        "poseidon",
        "big foot",
        "centaur",
        "cyclops",
        "goddess",
        "jupiter",
        "mermaid",
        "monster",
        "neptune",
        "pegasus",
        "phoenix",
        "unicorn",
        "vampire",
        "dragons",
        "loki",
        "odin",
        "werewolf",
        "witch",
        "tooth fairy",
        "santa claus"
      ],
      "famous person" => [
        "Angelina Jolie",
        "Bob Dylan",
        "Brad Pitt",
        "Bruce Lee",
        "Geronimo",
        "Green Day",
        "Kate Moss",
        "Lady Aaga",
        "Lil Wayne",
        "Ludacris",
        "Mc Hammer",
        "Tom Hanks",
        "David Beckham",
        "Steven Colbert",
        "Picasso",
        "Rihanna",
        "Van Gogh",
        "Justin Bieber",
        "Eminem",
        "Gandhi"
      ]
    }
end
