defmodule Fakeartist.Wordlist_DE do
  def wxWORDLIST,
    do: %{
      "Tier" => [
        "Ameise",
        "Ameisenbär",
        "Bär",
        "Gürteltier",
        "Dachs",
        "Biber",
        "Biene",
        "Vogel",
        "Stier",
        "Kalb",
        "Kamel",
        "Katze",
        "Gepard",
        "Schimpanse",
        "Kuh",
        "Kranich",
        "Krokodil",
        "Hirsch",
        "Dinosaurier",
        "Hund",
        "Delphin",
        "Esel",
        "Ente",
        "Adler",
        "Elefant",
        "Fisch",
        "Flamingo",
        "Fliege",
        "Fuchs",
        "Frosch",
        "Giraffe",
        "Ziege",
        "Goldfisch",
        "Gorilla",
        "Hamster",
        "Nilpferd",
        "Pferd",
        "Jaguar",
        "Känguru",
        "Katze",
        "Marienkäfer",
        "Leopard",
        "Löwe",
        "Eidechse",
        "Lama",
        "Hummer",
        "Mammut",
        "Affe",
        "Moskito",
        "Oktopus",
        "Strauß",
        "Otter",
        "Eule",
        "Austern",
        "Panda",
        "Panther",
        "Papagei",
        "Pfau",
        "Pelikan",
        "Pinguin",
        "Schwein",
        "Taube",
        "Stachelschwein",
        "Welpe",
        "Kaninchen",
        "Waschbär",
        "Ratte",
        "Rentier",
        "Nashorn",
        "Hahn",
        "Skorpion",
        "Möwe",
        "Seepferdchen",
        "Robbe",
        "Hai",
        "Schafe",
        "Garnelen",
        "Schnecke",
        "Schlange",
        "Spinne",
        "Tintenfisch",
        "Eichhörnchen",
        "Seestern",
        "Storch",
        "Schwan",
        "Kaulquappe",
        "Tiger",
        "Kröte",
        "Clownfisch",
        "Thunfisch",
        "Truthahn",
        "Schildkröte",
        "Geier",
        "Walross",
        "Wal",
        "Wolf",
        "Zebra",
        "Schildkröte",
        "Büffel",
        "Wels",
        "Huhn",
        "Glühwürmchen",
        "Mammut",
        "Strauß",
        "Pfau",
        "Pitbull"
      ],
      "Gebäude" => [
        "Flughafen",
        "Mehrfamilienhaus",
        "Bank",
        "Friseurladen",
        "Scheune",
        "Buchhandlung",
        "Bowlingbahn",
        "Bushaltestelle",
        "Casino",
        "Burg",
        "Dom",
        "Kirche",
        "Zirkus",
        "Gericht",
        "Kaufhaus",
        "Disco",
        "Feuerwache",
        "Tankstelle",
        "Krankenhaus",
        "Haus",
        "Bibliothek",
        "Leuchtturm",
        "Einkaufszentrum",
        "Villa",
        "Kino",
        "Museum",
        "Bürogebäude",
        "Opernhaus",
        "Palast",
        "Tierhandlung",
        "Polizeistation",
        "Post",
        "Gefängnis",
        "Restaurant",
        "Sägewerk",
        "Schule",
        "Supermarkt",
        "Tempel",
        "Theater",
        "Bahnhof"
      ],
      "Kleidung" => [
        "Bandana",
        "Gürtel",
        "Bikini",
        "Stiefel",
        "Fliege",
        "Mütze",
        "Mantel",
        "Kleid",
        "Ohrenschützer",
        "Augenklappe",
        "Brille",
        "Handschuhe",
        "Haargummi",
        "Hut",
        "Stirnband",
        "Jacke",
        "Jeans",
        "Knieschoner",
        "Handschuhe",
        "Halskette",
        "Arbeitskleidung",
        "Schlafanzug",
        "Partyhut",
        "Regenmantel",
        "Sandalen",
        "Schal",
        "Hemden",
        "Schuhe",
        "Rock",
        "Hausschuhe",
        "Turnschuhe",
        "Socken",
        "Sombrero",
        "Strümpfe",
        "Anzug",
        "Pullover",
        "Sweatshirt",
        "Badeanzug",
        "T-Shirt",
        "Krawatte",
        "Hose",
        "Unterhose"
      ],
      "Land" => [
        "Afrika",
        "Amerika/USA",
        "Bahamas",
        "Brasilien",
        "Kanada",
        "China",
        "Ägypten",
        "England",
        "Finnland",
        "Frankreich",
        "Deutschland",
        "Griechenland",
        "Hawaii",
        "Holland",
        "Indien",
        "Iran",
        "Irland",
        "Israel",
        "Italien",
        "Jamaika",
        "Japan",
        "Mexiko",
        "Marokko",
        "Nordkorea",
        "Pakistan",
        "Russland",
        "Schweiz",
        "Saudi-Arabien",
        "Schottland",
        "Südkorea",
        "Spanien",
        "Syrien",
        "Taiwan",
        "Thailand",
        "Türkei",
        "Vietnam"
      ],
      "Familie" => [
        "Tante",
        "Bruder",
        "Kinder",
        "Tochter",
        "Vater",
        "Enkelin",
        "Oma",
        "Großmutter",
        "Großvater",
        "Enkel",
        "Ehemann",
        "Mutter",
        "Neffe",
        "Nichte",
        "Eltern",
        "Schwester",
        "Sohn",
        "Stieftochter",
        "Stiefsohn",
        "Onkel"
      ],
      "Essen" => [
        "Apfel",
        "Banane",
        "Grill",
        "Brot",
        "Brownie",
        "Burger",
        "Burritos",
        "Karotte",
        "Käse",
        "Kirsche",
        "Schokolade",
        "Kokosnuss",
        "Spaghetti",
        "Pizza",
        "Lasagne",
        "Hotdog",
        "Chicken Nuggets",
        "Kuchen",
        "Abendessen",
        "Doritos",
        "Fast Food",
        "Pommes",
        "Würstchen",
        "Lutscher",
        "Frikadelle",
        "Omelett",
        "Pfannkuchen",
        "Erdnuss",
        "Kuchen",
        "Pflaume",
        "Brezel",
        "Sandwich",
        "Wurst",
        "Kegeln",
        "Sojasauce",
        "Salat"
      ],
      "Lebensmittel" => [
        "Spargel",
        "Avocado",
        "Baguette",
        "Bohnen",
        "Brokkoli",
        "Kekse",
        "Mais",
        "Kohl",
        "Camembert",
        "Sellerie",
        "Getreide",
        "Auberginen",
        "Grapefruit",
        "Trauben",
        "Honig",
        "Ketchup",
        "Zitrone",
        "Salat",
        "Makkaroni",
        "Melone",
        "Muffin",
        "Pilz",
        "Senf",
        "Nudeln",
        "Zwiebel",
        "Orange",
        "Birne",
        "Erbsen",
        "Pfeffer",
        "Gurke",
        "Ananas",
        "Popcorn",
        "Eis am Stiel",
        "Kartoffel",
        "Gurken",
        "Kürbis",
        "Rettich",
        "Meeresfrüchte",
        "Eis",
        "Spinat",
        "Erdbeere",
        "Tomaten",
        "Thunfisch",
        "Möhre",
        "Wassermelone",
        "Pfirsich"
      ],
      "Getränk" => [
        "Caipirinha",
        "Champagner",
        "Coca Cola",
        "Cosmopolitan",
        "Cuba Libre",
        "Rotwein",
        "Bier",
        "Kaffee",
        "Espresso",
        "Limonade",
        "Long Island Iced Tea",
        "Rivella",
        "Smoothie",
        "Sixpack",
        "Tee",
        "Tequila",
        "Tequila Sunrise",
        "Whisky",
        "Margarita",
        "Martini",
        "Mineralwasser",
        "Mojito",
        "Moscow Mule",
        "Ovomaltine",
        "Piña Colada",
        "Prosecco"
      ],
      "Instrument" => [
        "Akkordeon",
        "Bass-Drum",
        "Bass-Gitarre",
        "Banjo",
        "Dudelsack",
        "Fagott",
        "Bongos",
        "Cello",
        "Klarinette",
        "Kuhglocke",
        "Trommel",
        "Schlagzeug",
        "E-Gitarre",
        "Konzertflügel",
        "Flöte",
        "Glockenspiel",
        "Gong",
        "Gitarre",
        "Harmonika",
        "Harfe",
        "Pauken",
        "Laute",
        "Mandoline",
        "Oboe",
        "Klavier",
        "Piccolo",
        "Saxophon",
        "Pauken",
        "Triangel",
        "Posaune",
        "Trompete",
        "Tuba",
        "Ukulele",
        "Violine",
        "Xylophon"
      ],
      "Pop-Kultur" => [
        "Aladdin",
        "Aquaman",
        "Asterix",
        "Transformers",
        "Avatar",
        "Avengers",
        "Batman",
        "Bowser",
        "Catwoman",
        "Garfield",
        "Ironman",
        "König der Löwen",
        "Pikachu",
        "Star Trek",
        "Star Wars",
        "Twilight"
      ],
      "Beruf" => [
        "Wirtschaftsprüfer",
        "Schauspieler",
        "Künstler",
        "Sportler",
        "Autor",
        "Bäcker",
        "Bankier",
        "Barbier",
        "Kosmetikerin",
        "Metzger",
        "Kapitän",
        "Tischler",
        "Kassierer",
        "Chauffeur",
        "Koch",
        "Trainer",
        "Verbrecher",
        "Zahnarzt",
        "Direktor",
        "Arzt",
        "Schlagzeuger",
        "Ingenieur",
        "Bauer",
        "Feuerwehrmann",
        "Fischer",
        "Gangster",
        "Gärtner",
        "Turner",
        "Richter",
        "Rechtsanwalt",
        "Zauberer",
        "Postbote",
        "Mechaniker",
        "Milchmann",
        "Musiker",
        "Krankenschwester",
        "Maler",
        "Pilot",
        "Klempner",
        "Dichter",
        "Polizist",
        "Politiker",
        "Priester",
        "Prinzessin",
        "Drucker",
        "Professor",
        "Rockstar",
        "Seemann",
        "Verkäufer",
        "Sheriff",
        "Schuster",
        "Soldat",
        "Chirurg",
        "Schneider",
        "Lehrer",
        "Tierarzt",
        "Kellner",
        "Krieger",
        "Uhrmacher",
        "Ringer",
        "Attentäter",
        "Direktor",
        "Gangster",
        "Gärtner",
        "Zauberer",
        "Prinzessin",
        "Kellnerin",
        "Ringer",
        "Metzger",
        "Kapitän",
        "Kassierer",
        "Cowgirl",
        "Zahnarzt",
        "Schlagzeuger",
        "Turner",
        "Postbote",
        "Milchmann",
        "Maler",
        "Klempner",
        "Poolboy",
        "Sheriff",
        "Soldat",
        "Chirurg",
        "Lehrer",
        "Krieger",
        "Künstler",
        "Barbier",
        "Cowboy",
        "Arzt",
        "Bauer"
      ],
      "Sport" => [
        "Bogenschießen",
        "Leichtathletik",
        "Badminton",
        "Baseball",
        "Basketball",
        "Bowling",
        "Boxen",
        "Kanufahren",
        "Autorennen",
        "Radfahren",
        "Fechten",
        "Angeln",
        "Fußball",
        "Frisbee",
        "Golf",
        "Gymnastik",
        "Drachenfliegen",
        "Eishockey",
        "Pferderennen",
        "Speer",
        "Joggen",
        "Judo",
        "Springseil",
        "Karate",
        "Weitsprung",
        "Minigolf",
        "Motorradrennen",
        "Pingpong",
        "Polo",
        "Rudern",
        "Rugby",
        "Segeln",
        "Tauchen",
        "Schießen",
        "Skifahren",
        "Rodeln",
        "Snowboarden",
        "Squash",
        "Schwimmen",
        "Tischtennis",
        "Tennis",
        "Triathlon",
        "Volleyball",
        "Gewichtheben",
        "Baseball",
        "Hantel",
        "Fußball",
        "Torpfosten",
        "Golfclub",
        "Halfpipe",
        "Handball",
        "Eislaufen",
        "Springseil",
        "Weitsprung",
        "Minigolf",
        "Olympische Spiele",
        "Pingpong",
        "Rodeln",
        "Schwimmen",
        "Bogenschießen",
        "Bowling",
        "Fechten",
        "Angeln",
        "Homerun",
        "Speer",
        "Schiedsrichter",
        "Boxen"
      ],
      "Fahrzeug" => [
        "Flugzeug",
        "Fahrrad",
        "Boot",
        "Bus",
        "Auto",
        "Hundeschlitten",
        "Gabelstapler",
        "Golfcart",
        "Hubschrauber",
        "Pferd",
        "Jet",
        "Minivan",
        "Motorrad",
        "Porsche",
        "Rennwagen",
        "Ruderboot",
        "Segelboot",
        "Roller",
        "Schiff",
        "U-Bahn",
        "Taxi",
        "Abschleppwagen",
        "Traktor",
        "Bahn",
        "Dreirad",
        "LKW",
        "Einrad",
        "Zeppelin"
      ],
      "Waffe" => [
        "Atombombe",
        "Stacheldraht",
        "Bajonett",
        "Bazooka",
        "Blasrohr",
        "Bombe",
        "Pfeil und Bogen",
        "Kanone",
        "Katapult",
        "Kettensäge",
        "Schlagstock",
        "Armbrust",
        "Brecheisen",
        "Dynamit",
        "Granate",
        "Hammer",
        "Handgranate",
        "Pistole",
        "Messer",
        "Landmine",
        "Rakete",
        "Revolver",
        "Gewehr",
        "Säge",
        "Schere",
        "Schraubendreher",
        "Schrotflinte",
        "Speer",
        "Schwert",
        "Panzer",
        "Torpedo"
      ],
      "Ereignis" => [
        "Geburtstag",
        "Wahl",
        "Hanukkah",
        "Flohmarkt",
        "Bestattung",
        "Hochzeit",
        "Scheidung",
        "Wiedervereinigung"
      ],
      "Wertsachen" => [
        "Armband",
        "Kristall",
        "Diamant",
        "Smaragd",
        "Schmuck",
        "Aktienpapiere"
      ],
      "Spiele" => [
        "4 Gewinnt",
        "Air Hockey",
        "Backgammon",
        "Billard",
        "Black Jack",
        "Book of Ra",
        "Carcasonne",
        "Die Siedler von Catan",
        "Fake Artist Goes To New York :)",
        "Flipper",
        "Flunky-Ball",
        "Go",
        "Kreuzworträtsel",
        "Mau-Mau",
        "Monopoly",
        "Puzzle",
        "Quartett",
        "Risiko",
        "Rommé",
        "Roulette",
        "Russisch-Roulette",
        "Schach",
        "Scotland Yard",
        "Scrabble",
        "Snooker",
        "Sodoku",
        "Tic-tac-toe"
      ],
      "Spielzeug" => [
        "Hulahoop",
        "Schaukel",
        "Ballon",
        "Dreirad",
        "Gameboy",
        "Schaufel",
        "Teddybär"
      ],
      "Werkzeug" => [
        "Kettensäge",
        "Schere",
        "Pinzette",
        "Kompass",
        "Brecheisen",
        "Kehrblech",
        "Hefter",
        "Bohrmaschine",
        "Schraubenzieher"
      ],
      "Möbel" => [
        "Wasserbett",
        "Badewanne",
        "Stockbett",
        "Schrank",
        "Barhocker",
        "Bücherregal",
        "Kommode"
      ],
      "Pflegeprodukte" => [
        "Lippenstift",
        "Parfüm",
        "Shampoo",
        "Nagelfeile",
        "Sonnencreme",
        "Haarfarbe",
        "Haargel",
        "Mascara"
      ],
      "Medizin" => [
        "Krücken",
        "Zahnersatz",
        "Erste Hilfe",
        "Kopfschmerzen",
        "Krankenhaus",
        "Medikamente",
        "Seekrank",
        "Sonnenbrank",
        "Impfstoff",
        "Vitamine"
      ],
      "Pflanze" => [
        "Palme",
        "Tannenzapfen",
        "Pinie",
        "Primel",
        "Kaktus",
        "Algen",
        "Bambus",
        "Karotte",
        "Sellerie",
        "Kirsche",
        "Knoblauch",
        "Trauben"
      ],
      "Ort" => [
        "Hong Kong",
        "New York",
        "Moskau",
        "Zürich",
        "Basel",
        "Bern",
        "Berlin",
        "Paris",
        "Mallorca",
        "Amsterdam",
        "Hamburg",
        "Sydney",
        "Melbourne",
        "Las Vegas",
        "San Franciso",
        "Venedig",
        "Los Angeles",
        "Moskau"
      ],
      "Anatomie" => [
        "Wirbelsäule",
        "Stirn",
        "Schnurrbart",
        "Nasenhaar",
        "Schulter",
        "Skelett",
        "Tentakel",
        "Whisker",
        "Augapfel",
        "Augenbrauen",
        "Wimpern",
        "Kniescheibe",
        "Knöchel",
        "Magen",
        "Unibrow",
        "Penis"
      ],
      "Musik" => [
        "Dudelsack",
        "Gitarre",
        "Daft Punk",
        "Macarena",
        "Musikbox",
        "Skrillex",
        "Posaune",
        "Beatles",
        "Beyoncé",
        "Blondie",
        "Bon Jovi",
        "Schlagzeug",
        "Dubstep",
        "Nirvana",
        "Outkast",
        "Shakira",
        "Ukulele"
      ],
      "Mythologie" => [
        "Greif",
        "Atlantis",
        "Herkules",
        "Minotaurus",
        "Poseidon",
        "Big Foot",
        "Zentaur",
        "Zyklop",
        "Göttin",
        "Jupiter",
        "Meerjungfrau",
        "Monster",
        "Neptun",
        "Pegasus",
        "Phönix",
        "Einhorn",
        "Vampir",
        "Drachen",
        "Loki",
        "Odin",
        "Werwolf",
        "Hexe",
        "Zahnfee",
        "Weihnachtsmann"
      ],
      "Berühmte Person" => [
        "Angelina Jolie",
        "Bob Dylan",
        "Brad Pitt",
        "Bruce Lee",
        "Geronimo",
        "Green Day",
        "Kate Moss",
        "Lady Aaga",
        "Lil Wayne",
        "Ludacris",
        "McHammer",
        "Tom Hanks",
        "David Beckham",
        "Steven Colbert",
        "Picasso",
        "Rihanna",
        "Van Gogh",
        "Justin Bieber",
        "Eminem",
        "Gandhi"
      ],
      "Fiktionale Charaktere" => [
        "Homer Simpson",
        "Spiderman",
        "Frankenstein",
        "Darth Vader",
        "R2D2",
        "3CPO",
        "Luke Skywalker",
        "Barney Stinson",
        "Dexter Morgan",
        "Stromberg",
        "King Kong",
        "Godzilla",
        "Mickey Mouse",
        "Donald Duck",
        "Onkel Dagobert",
        "Alf",
        "Harry Potter",
        "Bob der Baumeister",
        "Winnie Puuh",
        "Spongebob Schwammkopf",
        "Ernie & Bert (Sesamstraße)",
        "Superman",
        "Catwoman",
        "Walter White"
      ],
      "Film und Fernsehen" => [
        "Django",
        "Kung-Fu Panda",
        "X-Men",
        "Iron Man",
        "Herr der Ringe",
        "Arielle die Meerjungfrau",
        "Der Zauberer von Oz",
        "Forrest Gump",
        "Der Terminator",
        "Harry Potter",
        "Der Davinci Code",
        "Clockwork Orange",
        "Shining",
        "Don Quijote",
        "Robinson Crusoe",
        "Sherlock Holmes",
        "The Matrix",
        "Die Lindenstraße",
        "Breaking Bad",
        "Stranger Things",
        "Game of Thrones"
      ]
    }
end
